### ISSUE TITLE
Stack trace on one of my endpoints

### ISSUE THREAD

**Issue by rotten** [Endava/cats#8]
As soon as cats starts up against one of my endpoints, it blows up:
```
[********* ][*****] ▶ start    Start fuzzing path /v1/my/endpointl
[********* ][*****] ✖ error    Something went wrong while running CATS!
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 14
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.endava.cats.model.factory.FuzzingDataFactory.lambda$addNewCombination$9(FuzzingDataFactory.java:320)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.endava.cats.model.factory.FuzzingDataFactory.addNewCombination(FuzzingDataFactory.java:318)
	at com.endava.cats.model.factory.FuzzingDataFactory.getPayloadCombinationsBasedOnOneOfAndAnyOf(FuzzingDataFactory.java:305)
	at com.endava.cats.model.factory.FuzzingDataFactory.generateSample(FuzzingDataFactory.java:289)
	at com.endava.cats.model.factory.FuzzingDataFactory.getResponsePayloads(FuzzingDataFactory.java:441)
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzDataForNonBodyMethods(FuzzingDataFactory.java:110)
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzingDataForGet(FuzzingDataFactory.java:87)
	at com.endava.cats.model.factory.FuzzingDataFactory.fromPathItem(FuzzingDataFactory.java:72)
	at com.endava.cats.CatsMain.fuzzPath(CatsMain.java:360)
	at com.endava.cats.CatsMain.startFuzzing(CatsMain.java:174)
	at com.endava.cats.CatsMain.doLogic(CatsMain.java:165)
	at com.endava.cats.CatsMain.run(CatsMain.java:143)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
	at com.endava.cats.CatsMain.main(CatsMain.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```
My API does not throw any errors when this happens.  Suggestions for what might cause this?

**Comment by en-milie** [comment]
Is there a way to share the endpoint? Keeping the structure and anonymize if needed. Seems like a oneOf/anyOf definition.

**Comment by rotten** [comment]
A bunch of my endpoints do this, only a few actually work.  I don't have an easy way to share it at this time.  I might be able to construct a standalone FastAPI instance that can reproduce the crash though.  It is worth a shot.  I'll see what I can post back.

**Comment by rotten** [comment]
I spun up a simple fastapi example with two GET endpoints that don't really do anything.  Now when I run cats both endpoints kick out an NPE.  I would have expected the simple endpoints to fuzzable.  First the API server:
requirements.txt
```
fastapi==0.65.2
uvicorn==0.14.0
```
server.py
```
from fastapi import Depends, FastAPI, Request

app = FastAPI()

@app.get('/')
async def read_root():
    return {'Hello': 'World'}

@app.get('/health')
async def api_health(request: Request):
    return 'OK'
```
The api server is started with
```
 uvicorn server:app
```
You can then hit http://localhost:8000/ and http://localhost:8000/health to see the api response.
If you go to http://localhost:8000/docs you can save the "/openapi.json" for use as the contract.  I tried it both as a json and converted it to a yml.
```
 ./cats.jar --contract=example_openapi.yml --server=http://localhost:8000
```
I tried specifying the paths individually, and leaving `--Paths` out of the argument list.

**Comment by rotten** [comment]
```$  ./cats.jar --contract=example_openapi.yml --server=http://localhost:8000

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

[********* ][*****] ● note     Proxy configuration to be used: DIRECT
[********* ][*****] ▶ start    Starting CATS, version 6.0.3-SNAPSHOT, build-time 2021-07-16T15:59:55.285 UTC
[********* ][*****] ● note     Processing configuration...
[********* ][*****] ℹ info     No security custom Fuzzer file. SecurityFuzzer will be skipped!
[********* ][*****] ℹ info     No custom Fuzzer file. CustomFuzzer will be skipped!
[********* ][*****] ℹ info     No reference data file was supplied! Payloads supplied by Fuzzers will remain unchanged!
[********* ][*****] ℹ info     No URL parameters supplied!
[********* ][*****] ℹ info     No headers file was supplied! No additional header will be added!
[********* ][*****] ▶ start    skipXXXForPath supplied arguments: []. Matching with registered fuzzers...
[********* ][*****] ☑ complete skipXXXForPath list after matching with registered fuzzers: []
[********* ][*****] ℹ info
[********* ][*****] ℹ info     Supplied arguments
[********* ][*****] ℹ info     contract: example_openapi.yml
[********* ][*****] ℹ info     server: http://localhost:8000
[********* ][*****] ℹ info     fuzzers: all
[********* ][*****] ℹ info     paths: all
[********* ][*****] ℹ info     skipPaths: empty
[********* ][*****] ℹ info     excludedFuzzers: empty
[********* ][*****] ℹ info     skipXXXForPath: []
[********* ][*****] ℹ info     skipFields: empty
[********* ][*****] ℹ info     httpMethods: empty
[********* ][*****] ℹ info     checkHeaders: false
[********* ][*****] ℹ info     checkFields: false
[********* ][*****] ℹ info     checkHttp: false
[********* ][*****] ℹ info     checkContract: false
[********* ][*****] ℹ info     fieldsFuzzingStrategy: ONEBYONE
[********* ][*****] ℹ info     maxFieldsToRemove: empty
[********* ][*****] ℹ info     edgeSpacesStrategy: trimAndValidate
[********* ][*****] ℹ info     sanitizationStrategy: sanitizeAndValidate
[********* ][*****] ℹ info     useExamples: true
[********* ][*****] ℹ info     reportingLevel: info
[********* ][*****] ℹ info     log: empty
[********* ][*****] ℹ info     printExecutionStatistics: false
[********* ][*****] ℹ info     timestampReports: empty
[********* ][*****] ℹ info     reportFormat: htmlJs
[********* ][*****] ℹ info     urlParams: empty
[********* ][*****] ℹ info     headers: empty
[********* ][*****] ℹ info     refData: empty
[********* ][*****] ℹ info     customFuzzerFile: empty
[********* ][*****] ℹ info     securityFuzzerFile: empty
[********* ][*****] ℹ info     proxyPort: 0
[********* ][*****] ℹ info     proxyHost: empty
[********* ][*****] ℹ info     sslKeystore: empty
[********* ][*****] ℹ info     sslKeystorePwd: empty
[********* ][*****] ℹ info     sslKeyPwd: empty
[********* ][*****] ℹ info     basicauth: empty
[********* ][*****] ☑ complete Finished parsing the contract in 84 ms
[********* ][*****] ⚠ warning
[********* ][*****] ⚠ warning 			 !!!! WARNING !!!!
[********* ][*****] ⚠ warning You are running with all Fuzzers enabled. This will take a long time to run!
[********* ][*****] ⚠ warning 		 Please check the CATS README page for slicing strategies!
[********* ][*****] ⚠ warning
[********* ][*****] ℹ info
[********* ][*****] ▶ start    Start fuzzing path /
[********* ][*****] ✖ error    Something went wrong while running CATS!
java.lang.NullPointerException: null
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzDataForNonBodyMethods(FuzzingDataFactory.java:106)
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzingDataForGet(FuzzingDataFactory.java:87)
	at com.endava.cats.model.factory.FuzzingDataFactory.fromPathItem(FuzzingDataFactory.java:72)
	at com.endava.cats.CatsMain.fuzzPath(CatsMain.java:360)
	at com.endava.cats.CatsMain.startFuzzing(CatsMain.java:174)
	at com.endava.cats.CatsMain.doLogic(CatsMain.java:165)
	at com.endava.cats.CatsMain.run(CatsMain.java:143)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346)
	at com.endava.cats.CatsMain.main(CatsMain.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```
When I get past the NPE, then I can go back to make an endpoint that throws my original exception.

**Comment by en-milie** [comment]
NPE is now fixed. Can you please check. I'm very interested on how the initial payload looks like. It seems something related to the way the swagger python library generates the documentation and how schemas are referenced.

**Comment by rotten** [comment]
Excellent!  Thanks!  I can confirm the NPE is gone.  Now I'll go back to building  my example to see if I can get that IndexOutOfBounds exeception again so we have an example demonstrating the issue.  This may take me a couple of days because I have a very full schedule for the next few days.

**Comment by rotten** [comment]
I believe this is the issue that is causing the IndexOutOfBounds errors:  https://github.com/tiangolo/fastapi/issues/240

**Comment by en-milie** [comment]
Is there a way to post an (anonymized) snapshot of the endpoint? I suspect is also around the naming of the schemas?

**Comment by rotten** [comment]
I'll see what I can do.

**Comment by rotten** [comment]
I'm still trying to reproduce this, whenever I get a chance, in a fastapi example outside the context of my application.  Unfortunately cats works fine on the examples I've been able to generate so far.

I was able to resolve the openapi formatting issue for the "exclusiveMinimum" field as references in the issue listed above by exporting a custom openapi.json .  (It is still not fixed without overriding the defaults.)

Even the latest version of cats still blows up almost instantly with the stack trace above.  So resolving that bug in the openapi.json output did not clear the issue.

Is there any easy way to insert additional debugging hints in the cats code to expose exactly what is causing this exception?  I'm not clear whether it is parsing the openapi.json file that is causing it to fail, or something in my endpoint itself.  It does not appear to ever actually hit the endpoint.

```
[********* ][*****] ✖ error    Something went wrong while running CATS!
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 14
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.endava.cats.model.factory.FuzzingDataFactory.lambda$addNewCombination$9(FuzzingDataFactory.java:320)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.endava.cats.model.factory.FuzzingDataFactory.addNewCombination(FuzzingDataFactory.java:318)
	at com.endava.cats.model.factory.FuzzingDataFactory.getPayloadCombinationsBasedOnOneOfAndAnyOf(FuzzingDataFactory.java:305)
	at com.endava.cats.model.factory.FuzzingDataFactory.generateSample(FuzzingDataFactory.java:289)
	at com.endava.cats.model.factory.FuzzingDataFactory.getResponsePayloads(FuzzingDataFactory.java:441)
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzDataForHttpMethod(FuzzingDataFactory.java:202)
	at com.endava.cats.model.factory.FuzzingDataFactory.getFuzzDataForPost(FuzzingDataFactory.java:170)
	at com.endava.cats.model.factory.FuzzingDataFactory.fromPathItem(FuzzingDataFactory.java:60)
	at com.endava.cats.CatsMain.fuzzPath(CatsMain.java:361)
	at com.endava.cats.CatsMain.startFuzzing(CatsMain.java:175)
	at com.endava.cats.CatsMain.doLogic(CatsMain.java:166)
	at com.endava.cats.CatsMain.run(CatsMain.java:144)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at com.endava.cats.CatsMain.main(CatsMain.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

I'll keep working on an example whenever I get a chance.  I just wanted you to know I haven't given up on it yet.

**Comment by rotten** [comment]
By adding:
```
System.out.println(key);
```
at line 320 of `/src/main/java/com/endava/cats/model/factory/FuzzingDataFactory.java`

I get these two rows:
```
dataANY_OF#/components/schemas/response_utils__JsonAPIDocDataItem
dataANY_OFnull
```
before it blows up.

It looks like the second row is failing because it is missing a `#`.

... still digging.

**Comment by rotten** [comment]
Ok, I found the part of the openapi.json that trips this exception:

**Comment by en-milie** [comment]
@rotten Thank you for the detailed information. I'll try to reproduce it locally and work on a fix.

**Comment by en-milie** [comment]
This is now fixed in https://github.com/Endava/cats/commit/59607819ae48ec3ea8ccd564dbd42e0ae6754b90
@rotten please give it a try when you have some time.

**Comment by luanacesar** [comment]
Hi Everyone, today I gave a try again and I’m still facing issues. First I got an error about not having the surefire package, then I got this error below. I used the Endava cats maven URL in the Pom file but I also used mine too, I got the same error in both. What should I do? Thank you for your help.


[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  02:30 min

[INFO] Finished at: 2021-08-18T08:42:53-04:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project cats: Failed to retrieve remote metadata com.endava:cats:6.0.5-SNAPSHOT/maven-metadata.xml: Could not transfer meta

data com.endava:cats:6.0.5-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/Endava/cats): transfer failed for https://maven.pkg.github.com/Endava/cats/com/endava/cats/6.0.5-SNAPSHOT/maven-metadata.xml:sun.se

curity.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fcwiki.apache.org%2Fconfluence%2Fdisplay%2FMAVEN%2FMojoExecutionException&data=04%7C01%7C%7C8a6483ac4cfd479ec7bf08d962476d27%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637648881179685740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cOZrK1gpZM3s%2BI79OqNYPXJ5gD5%2B7G3mxd%2FDYEjN4CE%3D&reserved=0>

----------------------------------------



<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
<configuration>
        <testFailureIgnore>true</testFailureIgnore>
</configuration>
</plugin>





Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by en-milie** [comment]
@luanacesar it seems you are trying to deploy cats. can you please run `mvn clean package` and let me know what happens?

**Comment by en-milie** [comment]
This is now released under: https://github.com/Endava/cats/releases/tag/cats-6.0.5
@luanacesar if you still have the other issue reported, please open another issue.
